### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/sprocrest#2]
Hey guys -- wondering if there are plans to develop this project further. Let me know what you'd like to do! -- Lauri

**Comment by valgog** [comment]
It is a very powerful tool and is being used in lots of current Zalando projects.

There are some things to do though. For example one has to check if it still works with the newest version of the PGJDBC driver.

**Comment by hjacobs** [comment]
@valgog I think you are mixing something up, this repo is not https://github.com/zalando/java-sproc-wrapper :smirk:

**Comment by valgog** [comment]
Oh, yes sorry, that one is just an unfinished experiment 😆

**Comment by lasomethingsomething** [comment]
Right. I'm still curious about this project's status. :) Does it have a future, and might it one day become useful for the world? @valgog

**Comment by valgog** [comment]
Of cause 😇

**Comment by lasomethingsomething** [comment]
Oh, I don't quite understand, @valgog. If you could rephrase differently, maybe I will ...

**Comment by valgog** [comment]
The thing is, that it was my experimental project and I thought it would be really nice to have go on working on this project. 

The problem like with any other project is that if nobody uses it, it is useless, literally useless.

There are some projects related to that approach, that some other people initiated either independently or after talking with me. And they use them. 

Even if I go on working on this project on my spare time, there is no guarantee, that it will be used in Zalando.

**Comment by lasomethingsomething** [comment]
I see, @valgog. :) What do you think about posting it to your personal page for now, and hopefully you'll be able to get some spare time to work on it again? 

OR: We pitch it to our team and the Postgres community to see if a contributor will show up and help you. I like this idea better than the first one I've offered, but it's up to you!

**Comment by lasomethingsomething** [comment]
@valgog @ebowman @CyberDem0n Hi all, given that this remains experimental, but might be something you want to keep public (or resurrect work on), I suggest that we move this project to: https://github.com/Zalando-Incubator. Please let me know if this is okay, and I'll do the honors. :)

**Comment by lasomethingsomething** [comment]
@valgog @ebowman @CyberDem0n Howdy -- just checking in on previous note :)

**Comment by lasomethingsomething** [comment]
@valgog @ebowman @CyberDem0n Guys, I'm going to move this to the Incubator if I don't hear back from one of you before next Wed, okay? I'll reconsider if one of you finishes this sentence in the README: "To automate the process of the" 

:)
